quarkus:
  datasource:
    db-kind: postgresql
    username: apipull
    password: apipullservice
    jdbc:
#      url: jdbc:postgresql://192.168.33.15:5434/apipull
      url: jdbc:postgresql://localhost:5434/apipull
  hibernate-orm:
    # database:
    #   # generation: update
    #   generation: drop-and-create
    log:
      sql: true
    # sql-load-script: import.sql
  log:
    level: INFO
    console:
      enable: true
    file:
      enable: true
      path: logs/a.log
      level: DEBUG
  container-image:
    build: true
    name: apipull
    group: marcincho
  
mp:
  openapi:
    extensions:
      smallrye:
        info:
          version: 1.0.0
          description: Github Api client with Quarkus and DB connection
          contact:
            name: Marcin
            email: github
          license:
            name: GNU GPLv3
            url: https://www.gnu.org/licenses/gpl-3.0.txt
    scan:
      disable: true


