spring:
    application:
        name: librarysearch
    datasource:
        url: jdbc:postgresql://192.168.33.15:5434/libraryms
        username: library
        password: libraryservice
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
logging:
    level:
        web: debug

